### ISSUE TITLE
Getting error percy snapshot 

### ISSUE THREAD

**Issue by ridhomard** [qahive/robotframework-puppeteer-percy#4]
I am getting this error when it executing percy snapshot 

`PuppeteerLibrary' object has no attribute 'get_current_page'`

**Comment by atthaboon** [comment]
What is your PuppeteerLibrary version and percy version that you install?

**Comment by ridhomard** [comment]
I am using **PuppeteerLibrary=2.1.10** & **robotframework-puppeteer-percy=0.1.0**

from what i can see , it can work if i am using old **PuppeteerLibrary** any version < **2.0.1**

**Comment by atthaboon** [comment]
@ridho-binary  Issued has been fixed in version 0.1.1.
Plz try to update and try again with the puppeteer latest version
